### ISSUE TITLE
Support for generic types

### ISSUE THREAD

**Issue by nicolasdalsass** [miloszpp/scala-ts#1]
Currently, the plugin will fail on the following class hierarchy :

```
case class Foo[T](a : T)
case class Bar(b: Foo[String], c:Foo[Int])
```
will give the following typings :

```
export interface IBar {
	c: IFoo;
	b: IFoo;
}

export class Bar {
	constructor(
		public c: Foo,
		public b: Foo
	) {}
}
export interface IFoo {
	a: string;
}

export class Foo {
	constructor(
		public a: string
	) {}
}
```

In which Foo as a string attribute, which is incorrect.

Please let me know if there's any plan for you to maintain this plugin (for example fixing this case :D)

Thanks for the great work anyway :)
Nico

**Comment by miloszpp** [comment]
Thanks for reporting an issue, it's great to know someone is actually using this project ;) I hope to find some time this week to look into this.

**Comment by nicolasdalsass** [comment]
That's great ! We have the very exact use case you mention in your readme of a scala backend and a TS frontend, so yeah, this project is of high interest to us :) 

I've fiddled with scala-js, but it's super heavyweight, and generates JS, not TS, whereas what you have here is exactly what we need ! 

I'll try to look into the code too, I'm just a bit shy cause I don't know anything about scala.reflect ^^

**Comment by nicolasdalsass** [comment]
FYI, I forked the project and pushed a version more fitting for our use cases.
The main very important regression is that I removed the class generation altogether, since our front-end guy doesn't want them :D 

Otherwise, it seems that it fixes Option types, and generic types handling. At least, it works for our class hierarchy ! 

If you want to pick whatever you want in this code, feel free, I didn't want to PR it since I removed half of the output in the process.

**Comment by miloszpp** [comment]
Awesome, thanks for contributing! I've been working on this feature since Monday and I was going to push my changes tomorrow. I will happily have a look at your code and see how you approached generic types.

Additionally, I will make class/interface generation configurable.

**Comment by miloszpp** [comment]
I just released version 0.3.0 which includes solution for this issue. @nicolasdalsass, I used some ideas from your fork - it helped me simplify the parser a lot. I mentioned you in the Credits section of the README. It would be really awesome if you could find some time to test it with your codebase.

**Comment by nicolasdalsass** [comment]
I will definitely test it! I'm off computer this week-end, so it'll be monday. Thanks for the kind words in the Readme :)

**Comment by nicolasdalsass** [comment]
The new version works great with our class hierarchy :)

I think I may tweak it a bit to use the "?" notation instead of "|null" for optional attributes, since it's a better fit for our use case (but I understand the concern with nested types in which we can't use "?").
