### ISSUE TITLE
Support for SBT 1.0

### ISSUE THREAD

**Issue by luisyng** [miloszpp/scala-ts#11]
Hi,

Currently, scala-ts is preventing us to upgrade our project to SBT 1.0. I've seen that that support has already been implemented in [returntocorp's fork](https://github.com/returntocorp/scala-ts/commits/master). Should I create a Pull Request to provide the support?

Thank you very much!
Luis

**Comment by miloszpp** [comment]
Hi Luis,

Please create a PR.

Thanks,
Milosz

**Comment by luisyng** [comment]
Hi Milosz,

Great. I just created [it](https://github.com/miloszpp/scala-ts/pull/12).

Thank you very much,
Luis

**Comment by miloszpp** [comment]
Hi Luis,

I’ve just published a new release (0.4.0 including the SBT 1.0 support.

Thanks,
Milosz

**Comment by luisyng** [comment]
Hi Milosz, 

Great! I will close the issue.

Thank you very much,
Luis
